### ISSUE TITLE
Error when selecting Defaults on setup. 

### ISSUE THREAD

**Issue by trancen** [archangelic/torrentcatcher#1]
When doing the setup and selecting the defaults a error was dumped.  I resolved the issue. 

In the BIN file torrentcatcher

lines marked with *, the original variable of "auth" was changed to "auth_in" 
-    auth_in = raw_input("Requires authentication [y/N]: ")
-    if not auth_in.strip():
      auth = False
-    if auth_in.lower().strip() == "y":
      auth = True
      user = raw_input("Username: ")
      password = getpass.getpass("Password: ")
  downloads = raw_input("Download directory: ")

**Comment by trancen** [comment]
![image](https://cloud.githubusercontent.com/assets/4571582/9366117/604d4804-4683-11e5-9d9f-547d95c524a0.png)

**Comment by archangelic** [comment]
Changes now pushed to pypi.
